### ISSUE TITLE
DeprecationWarning on Python 3.8+

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.index#30]
Python 3.8 and above show the following warning while running the tests:

```python
/.../zope/index/text/okapiindex.py:347: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  score(result, items, docid2len, idf, meandoclen)
```

`score` seems to be implemented in `C`, so it is not clear to me which auf the parameters is implicitly converted.

**Comment by mgedmin** [comment]
I wonder if this could be a missed `/` operator in the Python code somewhere?

**Comment by mgedmin** [comment]
It's docid2len.  It's supposed to map document IDs to document lengths (measured as the number of words in a document), but for some reason those numbers are floats.

https://github.com/zopefoundation/zope.index/blob/47103de327968b8f5f68588452d1054893661c46/src/zope/index/text/okascore.c#L98-L107

```
(Pdb) p list(docid2len.items())
[(1, 4.0), (2, 4.0)]
```

**Comment by mgedmin** [comment]
docid2len is an IFBTree, so it's unsurprising that it contains floats.

Perhaps it would be better to change the C code to accept floats.

**Comment by d-maurer** [comment]
Marius Gedminas wrote at 2020-4-14 09:13 -0700:
>It's docid2len.  It's supposed to map document IDs to document lengths (measured as the number of words in a document), but for some reason those numbers are floats.

It might be the logarithm of the number of words.

**Comment by mgedmin** [comment]
> It might be the logarithm of the number of words.

Not according to the code comments:

```c
/* ._docweight, maps d to # words in d */
```

```python
        # ._docweight for Okapi is
        # docid -> # of words in the doc
        # This is just len(self._docwords[docid]), but _docwords is stored
        # in compressed form, so uncompressing it just to count the list
        # length would be ridiculously expensive.
```

The reason it's an IFBTree is that it's defined in `baseindex.py`, where it represents an arbitrary document weight, with each kind of index having its own notion of what a weight is.  The "Okapi" index defines it as the number of words in the document, but doesn't change the actual data structure.

**Comment by icemac** [comment]
The future version referenced in the warning text of the issue description seems to be Python 3.10.
