### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [zopefoundation/zope.index#33]
Problem
---------
On aarch64, pip install zope-index builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install zope-index should download the wheels from pypi

Please let me know your interest on releasing aarch64 wheels. I can help in this. Are there any plans for moving to github actions?

**Comment by mgedmin** [comment]
This should be fixed by #34.

**Comment by icemac** [comment]
Probably a release is needed, so the wheels actually show up at PyPI. (Sorry ran out of time for today, so I cannot do it myself now.)

**Comment by icemac** [comment]
I just released https://pypi.org/project/zope.index/5.1.0/. It should be populated with the wheels in some minutes.
