### ISSUE TITLE
Zope index sometimes has a hard time installing

### ISSUE THREAD

**Issue by fgregg** [zopefoundation/zope.index#4]
Some of my users are having problems with zope.index not being found after successfully installing zope.index as a dependency. 

I have sneaking suspicion in may have to do with zope.index being a namespace package? Have you seen this kind of thing: https://github.com/datamade/dedupe/issues/410

Maybe related: https://github.com/datamade/dedupe/issues/268

**Comment by icemac** [comment]
The related issues are closed by now. So closing this one, too.

Please reopen if the issue still exists.
